<a href="https://colab.research.google.com/github/premkumarkora/Guvi-Numpy_tasks/blob/main/Guvi_Numpy_tasks_ipyn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [97]:
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
print(np.show_config)


1.21.6
<function show at 0x7f36da542290>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
nullVector_=np.zeros(10)
print(nullVector_)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
print("Size of Array :", np.size(nullVector_))
print("Byte Size :", nullVector_.itemsize)

Size of Array : 10
Byte Size : 8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
nullVector1_=np.zeros(10)
nullVector1_[4]=1
print(nullVector1_)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
arr= np.arange(10,49)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
print(arr[::-1])

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
arr2d = np.array([
    [0,1,2],
    [3,4,5],
    [6,7,8]
])
print(arr2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
arrind=[1,2,0,0,4,0] 
print(*np.nonzero(arrind))

[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
arrid = np.eye(3,3)
print(arrid)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
arr3by3 = np.random.random((3,3,3))
print(arr3by3)

[[[0.93074175 0.44487754 0.05702631]
  [0.33032262 0.72663459 0.90349062]
  [0.67671799 0.75078927 0.2971815 ]]

 [[0.63302428 0.35114231 0.88261501]
  [0.00135261 0.70020782 0.18017798]
  [0.37595127 0.44052798 0.65886674]]

 [[0.70570423 0.29953487 0.4821336 ]
  [0.16843348 0.40829676 0.63378805]
  [0.1325962  0.46653464 0.94898603]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
arr10by10 = np.random.random((10,10))
#print(arr10by10)
print("Max :", arr10by10.max())
print("Min :", arr10by10.min())

Max : 0.960883868595248
Min : 0.0034503510305980978


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
arrsize30 = np.random.random(30)
print("Mean :",arrsize30.mean())

Mean : 0.5394262600633908


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
arrbod=np.ones((5,5))
arrbod[1:-1, 1:-1]=0
print(arrbod)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
zeroBorder = np.zeros((3,3))
print(np.pad(zeroBorder, (1, 1), 'constant', constant_values=(1, 2))) # I have padded one's before the row and col / 2 ater row and col


[[1. 1. 1. 1. 2.]
 [1. 0. 0. 0. 2.]
 [1. 0. 0. 0. 2.]
 [1. 0. 0. 0. 2.]
 [1. 2. 2. 2. 2.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [112]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
arr8by8 = np.empty((8,8))
arr8by8[1::2,::2] = 1
#arr8by8[::2,::] = 1
print(arr8by8)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [113]:
print(np.unravel_index(99,(6,7,8)))  #Converts a flat index or array of flat indices into a tuple of coordinate arrays

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [114]:
checkerboardArr=np.tile(np.array([[0,1],[1,0]]),(4,4))  #Construct an array by repeating A the number of times given by reps.
print(checkerboardArr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [115]:
ranArr = np.random.random((5,5))
arrmax, arrmin = ranArr.max(), ranArr.min()
ranArr= (ranArr-arrmin)/(arrmax-arrmin)
print (ranArr)

[[0.104 0.673 0.148 0.603 0.048]
 [0.233 0.161 0.738 0.175 0.176]
 [0.189 0.817 0.    0.654 1.   ]
 [0.513 0.613 0.403 0.666 0.186]
 [0.309 0.549 0.681 0.306 0.653]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [116]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [118]:
arr5by3 = np.dot(np.random.random((5,3)), np.random.random((3,2)))
print (arr5by3)

[[0.339 0.192]
 [0.342 0.246]
 [0.458 0.277]
 [0.193 0.173]
 [0.482 0.345]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [119]:
arrZ = np.arange(11)
arrZ[(3 < arrZ) & (arrZ < 8)] *= -1
print(arrZ)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1)) # uses the sum function from Python
from numpy import *
print(sum(range(5),-1)) # uses the sun function from numpy


10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [120]:
Z<Z>Z  # illegeal Expresssion

ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [121]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.223e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
aa=np.random.randint(0,15,(10))
bb =np.random.randint(0,15,(10))
#print(aa)
#print(aa)
print(np.intersect1d(aa, aa))

[ 2  4 10 11  1 11 11 11  4  6]
[ 2  4 10 11  1 11 11 11  4  6]
[ 1  2  4  6 10 11]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
np.seterr(over='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
NO

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
TodayDate=np.datetime64('today', 'D')
print("Yesterday : ", TodayDate-1)
print("Today : ", TodayDate)
print("Tomorrow : ", TodayDate+1)

Yesterday :  2022-10-31
Today :  2022-11-01
Tomorrow :  2022-11-02


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
print(np.arange(datetime64('2016-07-01'), datetime64('2016-07-31')))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:

np.multiply(np.add(A,B),np.divide(-A,2))

-5.0

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
arr=np.random.random(3)*10
print(np.floor(arr))
print(np.trunc(arr))
print(np.ceil(arr))
print(arr.astype(int))

[6. 3. 1.]
[6. 3. 1.]
[7. 4. 2.]
[6 3 1]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
arr5by5 = np.zeros((5,5))
arr5by5 += np.arange(5)
arr5by5


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [10]:
def generator(): 
    for x in range(10):
        yield x
#print(*generator())
iterarr = np.fromiter(generator(), dtype=int, count=-1)
print (iterarr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [16]:
print(np.linspace(start=.1, stop=1, num=10, endpoint=False))

[0.1  0.19 0.28 0.37 0.46 0.55 0.64 0.73 0.82 0.91]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [11]:
arrsort = np.random.random(10)
arrsort.sort()
print(arrsort)

[0.1475842  0.35206513 0.39983848 0.47654521 0.47723113 0.4825937
 0.72406621 0.78035135 0.82686106 0.87705673]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [122]:
arr10 = np.arange(10)
np.add.reduce(arr10)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [19]:
Iarr = np.random.random(10)
IIarr = np.random.random(10)
np.allclose(Iarr, IIarr)

False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [22]:
immarr = np.zeros(10)
immarr.flags.writeable = False # writeable = False then the values of array cannot be changed

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [24]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X * 2 + Y * 2)
T = np.arctan2(Y, X)
print(R)
print(T)

[1.56348435 1.71462179 0.91120456 0.47806417 1.29579465 1.5796837
 1.92611977 1.46823654 0.83865891 1.38373401]
[0.31784313 0.96001308 0.55128828 0.70247393 0.00783337 0.46522092
 0.76398565 0.86628113 0.17041437 0.38346642]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [27]:
arrof10 = np.random.random(10)
#print(arrof10)
#print(arrof10.argmax())
arrof10[arrof10.argmax()] = 0
print(arrof10)

[0.56688735 0.24780786 0.13757153 0.06177827 0.66692743 0.24912122
 0.71555956 0.88475176 0.         0.42908367]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [38]:
for dtype in [np.int8, np.int32, np.int64]:
   print(dtype," :",np.iinfo(dtype).min)
   print(dtype," :",np.iinfo(dtype).max)
print("--------------------------------------------")
for dtype in [np.float32, np.float64]:
   print(dtype," :",np.finfo(dtype).min)
   print(dtype," :",np.finfo(dtype).max)
   print(dtype," :",np.finfo(dtype).eps)

<class 'numpy.int8'>  : -128
<class 'numpy.int8'>  : 127
<class 'numpy.int32'>  : -2147483648
<class 'numpy.int32'>  : 2147483647
<class 'numpy.int64'>  : -9223372036854775808
<class 'numpy.int64'>  : 9223372036854775807
--------------------------------------------
<class 'numpy.float32'>  : -3.4028235e+38
<class 'numpy.float32'>  : 3.4028235e+38
<class 'numpy.float32'>  : 1.1920929e-07
<class 'numpy.float64'>  : -1.7976931348623157e+308
<class 'numpy.float64'>  : 1.7976931348623157e+308
<class 'numpy.float64'>  : 2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [43]:
arr10 = np.random.rand(3,3)
np.set_printoptions(precision=3)
print(arr10)

[[0.094 0.909 0.724]
 [0.044 0.896 0.942]
 [0.931 0.88  0.463]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [50]:
arrof10 = np.arange(10)
inval = int(input("input Scalar :"))
#print(arrof10)
index = (np.abs(arrof10-inval)).argmin()
print(arrof10[index])

input Scalar :4
4


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [123]:
rgbarr = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),
                        ('color',    [ ('r', float, 1), ('g', float, 1), ('b', float, 1)])])
print(rgbarr)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [95]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)*2 + (Y-Y.T)*2)
print(D)

[[0.      nan   nan   nan 0.773 0.873   nan   nan 0.54    nan]
 [0.68  0.    0.652   nan 1.03  1.107 0.141 0.381 0.868   nan]
 [0.195   nan 0.      nan 0.797 0.894   nan   nan 0.574   nan]
 [0.89  0.574 0.869 0.    1.179 1.247 0.591 0.689 1.041   nan]
 [  nan   nan   nan   nan 0.    0.406   nan   nan   nan   nan]
 [  nan   nan   nan   nan   nan 0.      nan   nan   nan   nan]
 [0.666   nan 0.636   nan 1.02  1.098 0.    0.354 0.857   nan]
 [0.563   nan 0.529   nan 0.956 1.039   nan 0.    0.78    nan]
 [  nan   nan   nan   nan 0.553 0.686   nan   nan 0.      nan]
 [1.263 1.064 1.248 0.896 1.481 1.535 1.074 1.131 1.374 0.   ]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [96]:
fltarr = np.arange(10, dtype=np.float32)
intarr = fltarr.astype(np.int32, copy=False)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [101]:
missarr = np.genfromtxt("/content/drive/My Drive/Colab Notebooks/missing.txt", delimiter=",")
print(missarr)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [104]:
enarr = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(enarr):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [106]:
arrX, arrY = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(arrX*arrX+arrY*arrY)
sigma, mu = 1.0, 0.0
Garr = np.exp(-( (D-mu)*2 / ( 2.0 * sigma*2 ) ) )
print(Garr)

[[0.493 0.531 0.564 0.59  0.605 0.605 0.59  0.564 0.531 0.493]
 [0.531 0.577 0.62  0.655 0.675 0.675 0.655 0.62  0.577 0.531]
 [0.564 0.62  0.675 0.723 0.753 0.753 0.723 0.675 0.62  0.564]
 [0.59  0.655 0.723 0.79  0.839 0.839 0.79  0.723 0.655 0.59 ]
 [0.605 0.675 0.753 0.839 0.924 0.924 0.839 0.753 0.675 0.605]
 [0.605 0.675 0.753 0.839 0.924 0.924 0.839 0.753 0.675 0.605]
 [0.59  0.655 0.723 0.79  0.839 0.839 0.79  0.723 0.655 0.59 ]
 [0.564 0.62  0.675 0.723 0.753 0.753 0.723 0.675 0.62  0.564]
 [0.531 0.577 0.62  0.655 0.675 0.675 0.655 0.62  0.577 0.531]
 [0.493 0.531 0.564 0.59  0.605 0.605 0.59  0.564 0.531 0.493]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [108]:
m = 5
p = 3
zeroarr = np.zeros((m,m))
np.put(zeroarr, np.random.choice(range(m), p,replace=False),1)
print (zeroarr)

[[1. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [109]:
arri5 = np.random.rand(5, 10)
Yarr = arri5 - arri5.mean(axis=1, keepdims=True)
print(Yarr)

[[ 0.304  0.215 -0.041  0.217 -0.103  0.144 -0.336  0.155 -0.604  0.051]
 [ 0.216 -0.277  0.283  0.152 -0.032 -0.481  0.155 -0.048 -0.301  0.335]
 [ 0.373  0.131  0.386 -0.567  0.051  0.14  -0.269  0.302 -0.201 -0.347]
 [ 0.391  0.164 -0.193  0.271  0.284 -0.035 -0.279 -0.478  0.363 -0.487]
 [ 0.261 -0.032  0.103  0.044 -0.313 -0.211 -0.443 -0.049  0.215  0.425]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [110]:
ntharr = np.random.randint(0,10,(3,3))
print(ntharr[ntharr[:,1].argsort()])

[[6 4 8]
 [5 4 9]
 [8 9 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [111]:
nullarr = np.random.randint(0,3,(3,10))
print((~nullarr.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [52]:
arrof10 = np.random.random(10)
inval = float(input("input Scalar :"))
#print(arrof10)
index = (np.abs(arrof10-inval)).argmin()
print(arrof10[index])

input Scalar :.12
0.12882253637717178


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [75]:
vct1=np.ones(10)
vct2 = np.random.randint(0,len(vct1),10)
np.add.at(vct1, vct2, 1)
print(vct1)

[1. 3. 1. 1. 2. 2. 3. 3. 2. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [77]:
arrw = [1,2,3,4,5,6]
arry = [1,3,9,3,4,1]
binarr = np.bincount(arrw,arry)
print(binarr)

[0. 1. 3. 9. 3. 4. 1.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [89]:
arr4d = np.random.randint(0,10,(4,3,4))
#print(arr4d)
sumarr4d = arr4d.sum(axis=(-2,-1))
print(sumarr4d)

[63 62 50 50]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [90]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
Dsums = np.bincount(S, weights=D)
Dcounts = np.bincount(S)
Dmeans = Dsums / Dcounts
print(Dmeans)

[0.582 0.368 0.521 0.494 0.613 0.48  0.321 0.444 0.4   0.499]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [94]:
prodarr1 = np.random.randint(1,9,(3,3))
prodarr2 = np.random.randint(9,15,(3,3))
np.diag(np.dot(prodarr1, prodarr2))

array([107,  96, 112])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [124]:
arrA = np.ones((5,5,3))
arrB = np.ones((5,5))
print(arrA * arrB[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [125]:
swapA = np.arange(25).reshape(5,5)
swapA[[0,1]] = swapA[[1,0]]
print(swapA)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [126]:
binarr = np.bincount([1,1,2,3,4,4,6])
uniq = np.repeat(np.arange(len(binarr)), binarr)
print(uniq)

[1 1 2 3 4 4 6]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [127]:
negat = np.random.randint(0,2,100)
print(np.logical_not(negat, out=negat))


bolneg = np.random.uniform(-1.0,1.0,10)
print(np.negative(bolneg, out=bolneg))

[0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 0 1 0 1
 0 0 0 0 1 0 0 0 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 1 0 0
 1 1 1 0 0 1 1 0 0 0 1 0 0 1 1 1 0 1 0 1 0 1 1 0 0 0]
[ 0.561 -0.147 -0.987  0.349 -0.104  0.916 -0.717 -0.735  0.263  0.898]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [129]:
arr3by3 = np.arange(10)
rank = np.linalg.matrix_rank(arr3by3)
print(rank)

1


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [133]:
arr3by3 = np.random.randint(0,10,5)
print(np.bincount(arr3by3).argmax())

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [136]:
arrXL = np.random.randint(0,10,50000)
n=int(input("Type n ="))
print (arrXL[np.argsort(arrXL)[-n:]])

Type n =5
[9 9 9 9 9]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)